import { chromium } from "@playwright/test";
const [email, pw] = [process.env.E, process.env.P];
const b = await chromium.launch();
const p = await b.newPage();
const errs = [];
p.on("pageerror", (e) => errs.push(String(e)));
const base = "https://overrank.vercel.app";
await p.goto(base + "/leaderboard", { waitUntil: "networkidle" });
const teams = await p.locator("ol li").count();
console.log("leaderboard team cards:", teams, "| title:", await p.title());
await p.goto(base + "/teams/tech-titans", { waitUntil: "networkidle" });
console.log("team page members listed:", await p.locator('a[href^="/students/"]').count());
await p.goto(base + "/login", { waitUntil: "networkidle" });
console.log("login has email field:", await p.locator('input[name="email"]').count(), "| forgot link:", await p.getByRole("link", { name: "Forgot your password?" }).count());
await p.fill('input[name="email"]', email);
await p.fill('input[name="password"]', "wrong-password-123");
await p.getByRole("button", { name: "Sign in", exact: true }).click();
await p.getByText("do not match").waitFor({ timeout: 15000 });
console.log("wrong password rejected: yes");
await p.fill('input[name="password"]', pw);
await p.getByRole("button", { name: "Sign in", exact: true }).click();
await p.waitForURL(/\/admin/, { timeout: 30000 });
await p.waitForLoadState("networkidle");
console.log("admin signed in ->", p.url(), "| heading:", await p.getByRole("heading", { level: 1 }).first().innerText());
console.log("stat cards visible (students count text):", (await p.locator("main").innerText()).match(/STUDENTS\s*\n?\s*(\d+)/i)?.[1]);
await p.goto(base + "/forgot-password", { waitUntil: "networkidle" });
console.log("forgot page loads:", await p.getByRole("heading", { name: /forgot/i }).count());
console.log("page errors:", errs.length ? errs : "none");
await b.close();
