import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage();
const base = "https://overrank.vercel.app";
await p.goto(base + "/login", { waitUntil: "networkidle" });
await p.fill('input[name="email"]', process.env.E);
await p.fill('input[name="password"]', process.env.P);
await p.getByRole("button", { name: "Sign in", exact: true }).click();
await p.waitForURL(/\/admin/, { timeout: 30000 });
await p.waitForLoadState("networkidle");
await p.getByRole("button", { name: "Award points" }).first().click();
const d = p.getByRole("dialog", { name: "Award points" });
await d.getByPlaceholder("Search by name, ID or team").fill("Gayathri");
await d.getByRole("button", { name: /Gayathri V S/ }).click();
await d.getByLabel("Points").fill("10");
await d.getByLabel("Category").selectOption({ label: "Other" });
await d.getByLabel("Reason").fill("Live deployment check");
await d.getByRole("button", { name: "Award points" }).click();
await p.getByText("Points awarded to").waitFor({ timeout: 30000 });
console.log("award success screen shown: yes");
console.log("team result:", (await p.locator("[role=dialog]").innerText()).replace(/\s+/g, " ").slice(0, 160));
await p.getByRole("button", { name: "Done" }).click();
await p.goto(base + "/admin/points?q=Live deployment check", { waitUntil: "networkidle" });
console.log("ledger row visible:", await p.getByText("Live deployment check").first().isVisible());
await b.close();
